### PR TITLE
Added a clock and a new xmas effect

### PR DESCRIPTION
**Pull request by penfold42**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
Added a clock and a new xmas effect

the clock effect requires python pillow library

### CODE REVIEW

**Comment by brindosch** [comment]
speechless, i need to test this asap :)

**Comment by redPanther** [comment]
I also had the idea of a clock effect, but no time to do it. Thx you made it!

Is it possible to join both xmas effects? At least the python file. I don't like duplications ...

**Comment by brindosch** [comment]
also, the first xmas was not that good? cause it really just uses 1 white 1 red 1 white 1 red which is wrong, it should use a certain group of leds depending on strip length

**Comment by penfold42** [comment]
They're effects so it's all down to taste !

It didn't look that great on 600 LEDs on my house so I made a new one.

Rename it to Easter of you prefer *grin*

**Comment by penfold42** [comment]
Btw, there are probably better ways to do the clock.
If you know in advance that you have x LEDs in a circle you can be more accurate with the effect. This is what I did with my old perl script.

This one uses a bitmap and feeds an image to Hyperion so should work with any led setup.- 16x16, 60 led ring, 61 led concentric circles, strip around the tv... My loungeroom was very colorful last night with them all running.

**Comment by redPanther** [comment]
It's great that you use a bitmap, because my hyperion lamp looks like this:
https://github.com/redPanther/hypersim/blob/master/doc/images/snapshot_hyperion.config.matrix.png
(zick zack layout)

every effect that not based on "setColor" looks a bit strange.

**Comment by penfold42** [comment]
That's the other point of this effect - a better worked example than knight rider !

As an aside, I started with GD but it was really slow extracting the pixels. PIL has a nice gimme all
The data raw function (and many other features)

**Comment by brindosch** [comment]
which parts of pillow libs you need?

> from PIL import Image, ImageDraw, ImageColor

http://pillow.readthedocs.io/en/3.0.x/installation.html

**Comment by penfold42** [comment]
damn openelec ?

# dpkg -l | grep python-pil
ii  python-pil:armhf        2.6.1-2+deb8u2          armhf        Python Imaging Library (Pillow fork)

**Comment by brindosch** [comment]
OSMC "default"
ii python-pil:armhf 2.6.1-2+deb8u2 armhf Python Imaging Library (Pillow fork)

**Comment by redPanther** [comment]
Clock pie works on my raspi archlinux very well with python3 :-)
Can you add a rotation parameter in json file. My 12o'clock is mid left instead of mid top. My first pixel starts bottom left.

The clock hands crashes my hyperion, i will investigate the cause.

**Comment by brindosch** [comment]
So i wait with a merge :)
which lib installed you now @redPanther?
I want to strip it down as much as possible

**Comment by redPanther** [comment]
On archlinux python-pillow .... this wont help you because you are on debian base with python2

**Comment by penfold42** [comment]
Does pe_hnsnds crash ?

I'll see if I can build Hyperion with Python 3 and test it there too

**Comment by redPanther** [comment]
pie_hands crash to. Got the message

`AccessInit: hash collision: 22 for both 1 and 1`

**Comment by penfold42** [comment]
Maybe an easy fix
http://stackoverflow.com/questions/19349503/what-does-it-mean-in-python-accessinit-hash-collision-3-for-both-1-and-1

**Comment by redPanther** [comment]
tried it already. doesn't work. 
I tried the clock on my ubuntu 14.02 desktop system. hands doesn't crash, but shows nice black color.
The pie version schows only a red pie slice on the bottom and the clock hand for the seconds don't go around. "pie" works on my archlinux with py3 perfect ....

**Comment by penfold42** [comment]
Thanks - I'll have a look tonite.
I have 14.04 x86 and recent raspbian to edge with

**Comment by redPanther** [comment]
On my archlinux/py3 I've change this:

```
import PIL.Image
from PIL import ImageDraw,ImageColor

im = PIL.Image.new("RGB",(img_width, img_height))
```

than it works one time. If I select another effect afterwards hyperion crashes again.
ubuntu/py2 still not work

**Comment by redPanther** [comment]
hyperion defines an data  type named "Image" (include/utils/Image.h) I think this collides with PIL.Image like it does in the django cms where they have same problem.

**Comment by penfold42** [comment]
Nope - I can replicate this with 14.04 and forcing Python 3

Basically the first launch of an effect that uses clock.py works fine.

Select something else and then relaunch one of the clock effects and it fails.

It's like it's tried to import the module twice.

Am I correct in saying we have a single Python instance running all the time ?

**Comment by penfold42** [comment]
On second tjoughts maybe it's because I haven't cleaned up after myself when the script is stopped

**Comment by brindosch** [comment]
This was a auto-close after i deleted the branch to reduce everything to master for a easier cleanup

**Pull request closed without merging**
