### PR TITLE
Kodicheck: Add option for pause modus

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
This PR adds support to detect if kodi player is at pause state. This works with video, audio and pictures. The default value for this option is TRUE if not set at the .json (so no change to current behaviour). The default value for HyperCon is FALSE to get a nice function with the "rework" of the booteffect and new created "idle effect/color" which will be enabled by default.

**2.** If this changes affect the .conf file. Please provide the changed section
```
	/// KODICHECK CONFIG
	"xbmcVideoChecker" : 
	{
		"xbmcAddress" : "localhost",
		"xbmcTcpPort" : 9090,
		"grabVideo" : true,
		"grabPictures" : true,
		"grabAudio" : true,
		"grabMenu" : false,
		"grabPause" : false,
		"grabScreensaver" : true,
		"enable3DDetection" : true
	},
```
New option: "grabPause"

### CODE REVIEW

**Comment by redPanther** [comment]
Cool thx. Is there a list which kodi states exists?

Atm for play/pause/stop i use fhem plugin with hyperion remote to trigger effects/color in particular kodi state.

I have the idea that we can integrate json sending incl. new zeroconf feature in hyperipn addon. Then kodichecker inside hyperion is obsolete

**Comment by brindosch** [comment]
You want to remove the possibility to stop the grabbers?
There is currently a addon available which sends over json effects/colors.

**Comment by redPanther** [comment]
no of course not!
I mean, when hyperion kodi addon monitor kodi state, than it can send json messages to e.g. stop grabber, start effect, set color ... 

If kodi addon takes over the job of xbmcChecker class in hyperion, than xbmc checker is obsolete.
Next cool thing is, that with an extended json messaging we are ready for home automation (HA).
If somebody wants to that HA system xy switches hyperion off, then the person have to implement json sending in his HA system to do so.

**Comment by brindosch** [comment]
accepted, but the question is. Implement this at the current Addon? Or a new one?
Split grabbing and control? (control don´t need protob)

We need more people for the json interface ;)

**Comment by redPanther** [comment]
I would put it in one addon. This can be used for capturing and controlling hyperion. Perhaps some config stuff could be also implemented there.

But this are thoughts for the future and can't be implemented so quickly. i want to show a way what we can do in future.

Nice thing of this approach, when kodi changes somthing we don't have to modify hyperion, we have to modify the kodi addon to new kodi requirements - this is mor consequent!

**Pull request merged**
