### PR TITLE
Another option for Ws2812 - direct spi from the pi with 1 wire

### PR DESCRIPTION
**Pull request by penfold42**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
This adds a new led device type - ws2812spi
This (ab)uses the SPI functionality to send correctly timed bits out the MOSI pin.
NOTE: you need to disable core clock frequency scaling with force_turbo=1.
It doesnt matter what the core_clk frequency is, but it must be stable.
If your Pi is undervoltage, the Pi forcibly drops core_clk on you.

**2.** If this changes affect the .conf file. Please provide the changed section
A new device type with a default rate of 2857143
"type"       : "ws2812spi",
"rate"	: 2857143

### CODE REVIEW

**Comment by brindosch** [comment]
Great work!
Is this now just ws2812 or also ws2811? Not sure if there are big differences

**Comment by penfold42** [comment]
both - they're basically the same led controller but integrated with the leds on the 2812

**Comment by brindosch** [comment]
Good to know, thank you :)

**Comment by brindosch** [comment]
Added to HyperCon the new device "WS281X-SPI" layout from "WS2812B" (no options)

**Comment by brindosch** [comment]
@penfold42 
during compile on a Pi with reverted subproject commit id

```
In file included from /home/pi/hyperion/libsrc/leddevice/LedDeviceFactory.cpp:17:0:
/home/pi/hyperion/libsrc/leddevice/LedDeviceWs2812SPI.h:45:38: error: a brace-enclosed initializer is not allowed here before ‘{’ token
/home/pi/hyperion/libsrc/leddevice/LedDeviceWs2812SPI.h:50:9: sorry, unimplemented: non-static data member initializers
/home/pi/hyperion/libsrc/leddevice/LedDeviceWs2812SPI.h:50:9: error: ‘constexpr’ needed for in-class initialization of static data member ‘bitpair_to_byte’ of non-integral type
```
May you able to fix it? We wanted to start to check all commits if they do what they should :)

**Comment by penfold42** [comment]
weird - what do i need to do to reproduce this?
I cant see how the subproject revert would cause this.

Whats the gcc version?
heres mine: gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by brindosch** [comment]
A Raspbian wheezy or a 
Ubuntu 14.04 with gcc 4.8.2
(at least this is the current system) bot system throws these errors

**Comment by penfold42** [comment]
Thanks,

This is down the the gcc version and not the submodule. It might be as simple as adding "const"' or "static"

**Comment by penfold42** [comment]
compiles fine for me with ubuntu x86:
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
ill see if i can downgrade to 4.8.2

**Pull request merged**
