### PR TITLE
Logger

### PR DESCRIPTION
**Pull request by redPanther**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
add a logger and compiler class.
logger supports output to stdout and  syslog
profiler has timer to messure execution time of code parts

example for usage will come later in a wiki page.
currently this logger is not used, but now it's there and waiting :-)

**2.** If this changes affect the .conf file. Please provide the changed section
**3.** Reference a issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by penfold42** [comment]
Great work - i genuinely look forward to greppong for all the printf and cout statements !

**Comment by redPanther** [comment]
for those who can't wait:

**Logging**
use macros in include/utils/logger.h
Don't use the Logger class directly unless there is a good reason to do so.

```
// *** including
#include <utils/logger.h>

// *** creating
// get a logger, this will create a logger named MAIN with min loglevel INFO, DEBUG messages won't displayed
Logger * log_main = Logger::getInstance("MAIN");

// get a logger, this will create a logger named MAIN with min loglevel DEBUG,  all messages displayed

Logger * log_main = Logger::getInstance("MAIN", Logger::DEBUG);

// *** using
// basic
Debug( log_main, "hello folks!");
Info( log_main, "hello again!");
Warning( log_main, "something is crazy");
Error( log_main, "oh to crazy, aborting");

// a bit mor complex - with printf like format
Info( log_main, "hello %s, you have %d messages", "Dax", 25);

// conditional messages
WarningIf( (value>threshold), log_main, "Alert, your value is greater then %d", threshold );
```

**Profiling**
use macros in include/utils/profiler.h
Don't use the Profiler class directly unless there is a good reason to do so.

```
// *** include
#include "utils/Profiler.h"

//*** messure

// execution time of a block, time from macro name until the scope exists, nested scopes are possible
{
 ... code
PROFILER_BLOCK_EXECUTION_TIME;
 ... code
}

// global time messure withe named timers
// init timer and set start time - name must be uniq!
PROFILER_TIMER_START("SPI timer 1");

// get time until start
PROFILER_TIMER_GET("SPI timer 1");

// get time until start, if condition is fullfiled
PROFILER_TIMER_GET_IF( (transmission_complete == 1), "SPI timer 1");

```


```

**Comment by brindosch** [comment]
@redPanther 
Pi2 wheezy during compile
```
/home/pi/hyperion/libsrc/utils/Logger.cpp: In static member function ‘static Logger* Logger::getInstance(std::string, Logger::LogLevel)’:
/home/pi/hyperion/libsrc/utils/Logger.cpp:33:22: error: ‘class std::map<std::basic_string<char>, Logger*>’ has no member named ‘emplace’
libsrc/utils/CMakeFiles/hyperion-utils.dir/build.make:169: recipe for target 'libsrc/utils/CMakeFiles/hyperion-utils.dir/Logger.cpp.o' failed
make[2]: *** [libsrc/utils/CMakeFiles/hyperion-utils.dir/Logger.cpp.o] Error 1
CMakeFiles/Makefile2:967: recipe for target 'libsrc/utils/CMakeFiles/hyperion-utils.dir/all' failed
make[1]: *** [libsrc/utils/CMakeFiles/hyperion-utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by redPanther** [comment]
fck old debian. emplace is part of c++11 and hyperion use c++11 already. Ok I will replace the emplace with some older stuff. I wish wheezy would die out

http://www.cplusplus.com/reference/map/map/emplace/

**Comment by brindosch** [comment]
We could remove the compatibility for wheezy and move forward, if we just need to workaround again and again :)
Sadly the pi foundation killed wheezy just some months ago.

**Pull request merged**
