### PR TITLE
Allow random mood blobs color, set mood-blobs-full to random

### PR DESCRIPTION
**Pull request by pdf**
Small change to allow a random start hue for mood blobs - adds a bit of
spice instead of starting at the same color every time.

### CODE REVIEW

**Comment by brindosch** [comment]
Thank you :)

**Comment by pdf** [comment]
Thank you! :wink:

Might be worth adding a `CONTRIBUTING.md` or similar with a note about the preferred PR target branch to reduce your issue churn a little.

**Comment by brindosch** [comment]
Hm, yes you are right :)
I placed it already at the pull requests template, but it might be not that visible :)

**Comment by pdf** [comment]
Ah right, I didn't see the template because I use [hub](https://hub.github.com/) from the CLI.

**Pull request merged**
