### PR TITLE
zeroconf on by default, compiler error on x86

### PR DESCRIPTION
**Pull request by penfold42**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
zeroconf on by default
zeroconf dynamic link on x86 to fix compile failure

**2.** If this changes affect the .conf file. Please provide the changed section
nope

**3.** Reference a issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

dynamic link  zeroconf by default

### CODE REVIEW

**Comment by brindosch** [comment]
zeroconf shouldn´t be mandatory for V1.

**Comment by brindosch** [comment]
may you able to remove the zeroconf on by default part?

**Comment by penfold42** [comment]
done

**Comment by brindosch** [comment]
thanks

**Pull request merged**
