### PR TITLE
Fixing Check if LED Color not Black

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
Fixing the detection of the color Black
**2.** If this changes affect the .conf file. Please provide the changed section
no
**3.** Reference a issue (optional)
#701 
Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Oh, hm.
Now i have a problem. the beta is currently filled with some v2 code.
*needtothinkaboutit*

**Comment by penfold42** [comment]
Is master still clean ? Merge it there and delete beta.

Well only have bug fixes in 1.x

**Comment by redPanther** [comment]
shouldn't this fixed in hyperion.ng (the upcomming hyperion) too?

**Comment by brindosch** [comment]
yes
most PRs needs to be c/p to ng.

**Pull request merged**
