### PR TITLE
add zeroconf support based on qt4 libraries

### PR DESCRIPTION
**Pull request by penfold42**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
This adds avahi/zeroconf/bonjour support to hyperiond so apps can find it more easily
**2.** If this changes affect the .conf file. Please provide the changed section
Added config options to jsonServer and protoServer. if omitted, sensible defaults are used
        "jsonServer" :
        {
                "port" : 49444,
                "mDNSDescr" : "hyperiond jsonServer blah de blah",
                "mDNSService" : "_hyperiond_json._tcp"
        },
**3.** Reference a issue (optional)

Example:
root@Penfold42MediaPlayer:~# avahi-browse -r _hyperiond_json._tcp
+  wlan0 IPv4 Penfold42MediaPlayer                           _hyperiond_json._tcp local
=  wlan0 IPv4 Penfold42MediaPlayer                           _hyperiond_json._tcp local
   hostname = [Penfold42MediaPlayer.local]
   address = [10.0.0.77]
   port = [19444]
   txt = []

### CODE REVIEW

**Comment by brindosch** [comment]
GREAT WORK!

txt = []
A field to add more information? Like the current loaded config name?

What in specific is sensible? This affects "all" configs, cause no old install will get a new config.json (i assume this now - the color calibration was the last "real reason" for a user to create really a new one)
We should think about a full "feature" set by default and a opt out via config?
Not sure what is better for the "default" user and updaters, not that people run into issues with the new apps or don´t get all informations which are interesting to provide a app.
What do you think?

@RickDB 
and go :+1:  ;)

**Comment by brindosch** [comment]
I assume this is still the final package list?

libavahi-common-dev:armhf
libdbus-1-dev:armhf
libavahi-client-dev:armhf
libavahi-core-dev:armhf
libavahi-compat-libdnssd1:armhf
libavahi-compat-libdnssd-dev:armhf
libavahi-qt4-1:armhf
libavahi-qt4-dev:armhf
avahi-utils:armhf

**Comment by penfold42** [comment]
The defaults if omitted are the system host name and _hyperiond_json._tcp 

I'm not sure I like the config file name in the advertisement - maybe a better choice is the device name field ?

If you want the config file name, we should include it in the server info that you can query via Json

**Comment by brindosch** [comment]
Hm, this is also possible.
My idea behind is to determine which config is used from which hyperion instance if you use the forwarder. Yes you could say use the port config to remember, but this is not really well?

**Comment by penfold42** [comment]
maybe we can use instance@hostname for the main record by default (where instance is stored in the hyperiond.config.json file
you can be much more descriptive then

**Comment by brindosch** [comment]
now i get it!
```
	"device" :
	{
		"name"       : "MyPi",
		"type"       : "apa102",
		"output"     : "/dev/spidev0.0",
		"rate"     : 1000000,
		"colorOrder" : "bgr"
	},
```
read this name, we have no field for this at hypercon, i will add one! 
+3  for your idea
:)

**Comment by penfold42** [comment]
regarding library dependencies, I grabbed another Pi to build on

In file included from /home/penfold/hyperion/libsrc/bonjour/bonjourserviceregister.cpp:30:0:
/home/penfold/hyperion/include/bonjour/bonjourserviceregister.h:37:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>

# apt-get install libavahi-compat-libdnssd-dev
The following extra packages will be installed:
  libavahi-client-dev libavahi-common-dev libavahi-compat-libdnssd1 libdbus-1-dev pkg-config
The following NEW packages will be installed:
  libavahi-client-dev libavahi-common-dev libavahi-compat-libdnssd-dev libavahi-compat-libdnssd1 libdbus-1-dev pkg-config

Linking CXX executable ../../bin/hyperiond
/usr/bin/ld: cannot find -lavahi-core
/usr/bin/ld: cannot find -lavahi-qt4

# apt-get install libavahi-qt4-dev

The following extra packages will be installed:
  libavahi-qt4-1
The following NEW packages will be installed:
  libavahi-qt4-1 libavahi-qt4-dev

Linking CXX executable ../../bin/hyperiond
/usr/bin/ld: cannot find -lavahi-core

# apt-get install libavahi-core-dev
The following NEW packages will be installed:
  libavahi-core-dev

**Comment by brindosch** [comment]
yes, thank you

**Comment by penfold42** [comment]
[root@spare]# avahi-browse -a | grep hyper
+   eth0 IPv4 MyPi @ PenfoldMediaPlayer                    _hyperiond_proto._tcp local
+   eth0 IPv4 MyPi @ PenfoldMediaPlayer                    _hyperiond_json._tcp local
^CGot SIGINT, quitting.

**Comment by RickDB** [comment]
@penfold42 Nice work!

@brindosch Aye aye captain :P , concept app (cross platform excluding iOS for license limitation) will be done later this week with the basics in it and hopefully auto-discover but need to test further first :)

**Comment by brindosch** [comment]
lets test!

**Comment by brindosch** [comment]
wow, raspbian wheezy needs much stuff :)
```
root@raspberrypi:/home/pi# apt-get install libavahi-qt4-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libavahi-qt4-1 libgl1-mesa-dev libglu1-mesa-dev libmysqlclient18
  libpthread-stubs0 libpthread-stubs0-dev libqt4-declarative libqt4-designer
  libqt4-dev libqt4-dev-bin libqt4-help libqt4-opengl libqt4-opengl-dev
  libqt4-qt3support libqt4-script libqt4-scripttools libqt4-sql
  libqt4-sql-mysql libqt4-test libqt4-xmlpatterns libqtwebkit-dev libx11-dev
  libx11-doc libxau-dev libxcb1-dev libxdmcp-dev libxext-dev mesa-common-dev
  mysql-common qt4-linguist-tools qt4-qmake x11proto-core-dev
  x11proto-input-dev x11proto-kb-dev x11proto-xext-dev xorg-sgml-doctools
  xtrans-dev
Suggested packages:
  libqt4-declarative-folderlistmodel libqt4-declarative-gestures
  libqt4-declarative-particles libqt4-declarative-shaders qt4-qmlviewer
  firebird-dev libmysqlclient-dev libpq-dev libsqlite0-dev libsqlite3-dev
  qt4-dev-tools qt4-doc unixodbc-dev libxcb-doc libxext-doc
The following NEW packages will be installed:
  libavahi-qt4-1 libavahi-qt4-dev libgl1-mesa-dev libglu1-mesa-dev
  libmysqlclient18 libpthread-stubs0 libpthread-stubs0-dev libqt4-declarative
  libqt4-designer libqt4-dev libqt4-dev-bin libqt4-help libqt4-opengl
  libqt4-opengl-dev libqt4-qt3support libqt4-script libqt4-scripttools
  libqt4-sql libqt4-sql-mysql libqt4-test libqt4-xmlpatterns libqtwebkit-dev
  libx11-dev libx11-doc libxau-dev libxcb1-dev libxdmcp-dev libxext-dev
  mesa-common-dev mysql-common qt4-linguist-tools qt4-qmake x11proto-core-dev
  x11proto-input-dev x11proto-kb-dev x11proto-xext-dev xorg-sgml-doctools
  xtrans-dev
0 upgraded, 38 newly installed, 0 to remove and 0 not upgraded.
Need to get 18.6 MB of archives.
After this operation, 72.9 MB of additional disk space will be used.

```

**Comment by penfold42** [comment]
The joys of obsolete releases !

**Comment by brindosch** [comment]
hang on a pi2 with wheezy now

> /usr/bin/ld: cannot find -lavahi-qt4
hm, searched/played around - no idea what i could install?

**Comment by penfold42** [comment]
apt-get install libavahi-qt4-dev

**Comment by brindosch** [comment]
so sorry. sometimes you should follow the tired feeling and just go sleeping :)

**Comment by penfold42** [comment]
unlike my last commit at 1.30 am??? *grin*

**Comment by brindosch** [comment]
of course yes!
hm, this damn crosscompile i hate it!
i struggle at
````
/hyperion/include/bonjour/bonjourserviceregister.h:37:20: fatal error: dns_sd.h: file or dir not found
 #include <dns_sd.h>
                    ^
compilation terminated.
```
I compiled with success on a Pi2, this error is at the Pi compile during crosscompile
i rsynced already the new /usr and /lib from the Pi.
X64 compile works

This error is easy! or not...
need to fiddle around to check the libs

**Comment by redPanther** [comment]
when starting I get following message:

```
*** WARNING *** The program 'hyperiond' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=hyperiond>
```

Is it possible to use not the compat layer, so we are ready for the future?

**Comment by brindosch** [comment]
yes confirmed. log wars :)
If we need qt5, we just do it. Don´t invest too much time :)
this is a work in progress project and any dev is always welcome, if the devs could do some stuff better with qt5 we switch!

**Comment by penfold42** [comment]
I won't spend the time to suppress the warning unless it's a 2 minute fix.

I've started looking at the qt5 library again

**Comment by redPanther** [comment]
I don't look into this topic deeply. if using qt5 fixes this issue, then great.
My aim is to avoid using old/depcracated interfaces so we don't have trouble in future. Don't invest time in that if qt5 fixes this issue

**Comment by brindosch** [comment]
I wonder how i can add a TXT record, as there is no documentation about this. There is a empty qString(), but adding something seems to create a broken/hidden entry. Do you may have a clue about it? It can't be to hard...

**Comment by penfold42** [comment]
It shouldn't be - I know I looked at this a year ago...
... and gave up !

**Comment by brindosch** [comment]
I digged, it was a lot of fun...    _not_ :)
Here are the results.

The current impl is based on the comp layer of avahi (dns_sd.h) - libahavi-compat-libdnssd1
This is the argument list with docu of the register function we call -> https://github.com/jbagg/QtZeroConf/blob/master/bonjour-sdk/dns_sd.h#L1024

Maybe a migration to the native avahi impl might be better instead.
Here is the docu for ref: https://www.avahi.org/doxygen/html/publish_8h.html#acb05a7d3d23a3b825ca77cb1c7d00ce4
Here a example based on it: http://avahi.org/doxygen/html/client-publish-service_8c-example.html
Here a QT wrapper which doesn't ref to compat-lib: https://github.com/johanneshilden/qtzeroconf

To keep it noticed, i added all links here :)
I will do some tests soon TM :)

**Pull request merged**
