### PR TITLE
debian package

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
Latest change of "hyperiond can start multiple instances by it's own" is not compatible with current service files.
In debian packages support for /opt installation is completely removed. hypercon users must wait until hypercon gets support - or don't use debian package.
I sugegst advertising deb package for hyperion 2.0.
If hyperiond service is running, it will be restarted automaticly, otherwise (first install) you will be informed that you have to check your config.
If you have hyperion in /opt to (old installation), then a warning will be display at end of deb package postinstall.

**2.** If this changes affect the .conf file. Please provide the changed section
no new config options, but as .deb package user you have to check your config and set path for effects

**3.** Reference a issue (optional)
#640 

output of installation when hyperiond is running (upgrade)

```

(Lese Datenbank ... 285889 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von hyperion-1.3.0-Linux-ambilight.deb ...
Entpacken von hyperion-ambilight (1.3.0) über (1.3.0) ...
hyperion-ambilight (1.3.0) wird eingerichtet ...
--- hyperion ambilight postinstall ---
- install configuration template
INFO: /etc/hyperion/hyperion.config.json exists, new version copied to /etc/hyperion/hyperion.config.json.new
- init deamon: upstart
hyperion stop/waiting
INFO: /etc/init/hyperion.conf exists, new version copied to /etc/init/hyperion.conf.new
hyperion start/running, process 16663
-----------------------------------------------------------------------------
- hyperion is installed, please check your configuration in /etc/hyperion/  -
-----------------------------------------------------------------------------

```

### CODE REVIEW

**Comment by brindosch** [comment]
I will initiate a config move from /opt/hyperion/config to /etc/hyperion
I didn´t mentioned that.
I am sorry. So people are forced to use a new hypercon version. The dir /opt/config and /opt/init.d will be removed cause they are just used temporarily

We could move to .deb packages right now too :)
(if they are ready to perform all steps from the install script)

**Comment by redPanther** [comment]
cool :-) so lets test ... lots of PRs today :-)

whats missing is the dependency list of the deb package. avahi supports adds new dependencies too...

**Comment by penfold42** [comment]
I think the dependencies are build time only because we are statically linking

An ldd doesn't list any avahi run time libraries

**Comment by redPanther** [comment]
added dependencies to: libusb-1.0-0, libpython2.7, libc6
not tried to use the raspi .deb, because I have no debian on raspi.

perhaps It's  time to get an rpi3 and take my pi1 for experiments ;-)

**Comment by brindosch** [comment]
Pi1? 60 minutes compile? :)

Could you remove the opt path instead? (service files)

**Comment by redPanther** [comment]
done. no /opt defaults anymore (but of course adjustable via service files and config)

**Comment by brindosch** [comment]
@redPanther 
thank you, regarding the effect linking. Does this work with OpenELEC too? No?
I would add it to HyperCon too, so we could move the hyperion dir later. To remove the static linking
A one-line solution would be great. :)

**Comment by redPanther** [comment]
What you mean with static linking? E.g. avahi libs are staticly linked into hyperion, this is a completly other thing. What I did was making a symbolic link from  usr/share/hyperion/effects to /opt/hyperion/effects. This is possible with every unix filesystem using the 

ln -s target link-name

Command. This should be possible with openelec to.

**Comment by brindosch** [comment]
Oh, i am sorry, i just messed around with the phrases :) yes of couse symbolic

Hm, the truth is, we are at the point where we could move right now /bin and /effects to /usr/share/hyperion

Is this the preferred linux way - location?

I just need to ensure to edit all old configs and service files to be as much compatible as possible.
This needs some work and testing

**Comment by redPanther** [comment]
almost every linux distro makes it /etc /usr way. *elec is special, this is not a normal linux distro. I put everything in /storage and openelec not using service files (perhaps I'm wrong?) - I know only this way

**Comment by brindosch** [comment]
1. It is impossible to place something at /usr/ which is very sad, we can´t reduce the workarounds for openelec? I remove of the OpenELEC part of the hypercon ssh tap would be great.

Is there another away to get symlinks?

2. Libreelec uses a systemd way, not sure if we could "port" this to openelec.

In general i would prefer a cleaner solution for every platform. also to strip down documentation and options. (every "system" option is a point to fail - ssh system selection is not done right from everyone)

**Comment by redPanther** [comment]
welcome to linux world ;-) there is no - and will never be - a one fits all solution. (thatswhy the distributor provides the binaries, not the developer)
we can't port systemd to openelec. 

What I wonder is, why we dont bring all hyperion files with a kodi addon. then hyperion can be started with the addon on kodi start. Then we don't have to tinker with shell commands. Using a python way for starting hyperion executable is mutch cleaner and easier to install.

The configuration could be modified over json - we already have a json writer active in hyperion. Then there is no need for ssh tweaks.

for the debian/buntu people let them install the deb and after rebot/service start you can set your config via hypercon

**Comment by tpmodding** [comment]
that would be my choice too...all-in-one hyperion kodi addon, with bins efx and a gui for the config part...that would be awesome! we should talk about that in the forum

**Comment by brindosch** [comment]
*plop*
this idea is a good one, but i have no python experience
1. I am not sure if this is allowed at the official kodi repo (download / install bins and update them easily - we could push notifications too? LIKE!
2. we are not allowed to push new addons to earlier jarvis
3. if we need our own kodi repo, we could host one, but installation of external repo is additional work for a user
4. Hyperion log upload (how?)
5. Start wizard to calibrate Hyperion (let the wizard show the pictures)
6. V4L2 calibration wizard (?)

If we could add the possibility to write via JSON to the current loaded config the calibration values - WIN

**Comment by penfold42** [comment]
What if don't run kodi ?

**Comment by brindosch** [comment]
Use the command line install
:)

**Comment by redPanther** [comment]
Or the deb pavlsge

**Comment by brindosch** [comment]
OT: Is there a reason why this is set at the root CMakeLists.txt
```
onfigure_file(bin/install_hyperion.sh ${LIBRARY_OUTPUT_PATH} @ONLY)
configure_file(config/hyperion.config.json ${LIBRARY_OUTPUT_PATH} @ONLY)
configure_file(config/hyperion_x86.config.json ${LIBRARY_OUTPUT_PATH} @ONLY)
```
i delete these lines now?

@redPanther 
could you undo every change at the service files and the two .jsons?
I need to push everything in one PR and just at the point of release.

**Comment by redPanther** [comment]
the configure_file lines are obsolete now.
with configure_file you can kind of copy with search and replace. This is extremely useful when you compile and want to set e.g. options in that file depending on cmake variables. (or doing other crazy stuff like build  dynamic c++ source code depending on cmake options or external resources)

In our case, when setting CMAKE_INSTALL_PREFIX (base prefix for install files), then this could be used to set the effects path in the config file.
But I think in this case the configure file was kind of misused. It seems the inventor want to copy files during "make" time and didn't think of using make install or the cmake file copy command.


I will make revert on desired files...

**Comment by redPanther** [comment]
reverted

**Comment by brindosch** [comment]
https://github.com/hyperion-project/hyperion/pull/672

**Pull request merged**
