### PR TITLE
big code cleanup.

### PR DESCRIPTION
**Pull request by redPanther**
mostly line endings and indentions.
No functional changes - except protobuffer is mandatory and not optional now.

would be good if we check any upcoming PR if following rules are matched:
- use QT wherever it's possible (except there is a good reason)
- use unix line endings (not windows)
- indent your code with TABs instead of spaces
- follow this rule for curly brackets (current code is now fixed for that)
```
bad:
if (conditon) {
  code
}

good:
if (condition)
{
 code
}

```
the rules above are from tvdzwan's initial code - most code is written in this way. New code should follow this - except we (maintainers/community) decide something else.

I suggest a file named CODING_STYLE.md in hyperion main directory. In this file we should write rules  like above. this is necessary  for new developers. We should persist on that rules, because maintaining code that follows differnt coding styles is a hell

### CODE REVIEW

**Comment by penfold42** [comment]
Good timing - I'll have to get all my branches re-ported across anyway

**Comment by stefansaraev** [comment]
humh. any chance we can have protobuf as optional dependency again ?

**Comment by penfold42** [comment]
What do you lose with no protobuf ?

**Comment by redPanther** [comment]
We need some interprocess communication. Protobuf is our method to do that. We need it!

In future we want to split the core from e.g. grabber, effect engine. With no ipc we get a problem.

**Comment by stefansaraev** [comment]
> We need some interprocess communication. Protobuf is our method to do that. We need it!

I see, thanks @redPanther 

in that case, having an option to use external native protoc compiler + external headers/lib would be great :)

current way (having to do native hyperion build just for hyperion) is a bit troublesome (and overkill, imo, for just one native dependency) for embedded distros like OpenELEC / LibreELEC. it would require having ALL hyperion dependencies also built for native..

**Comment by redPanther** [comment]
perhaps it is possible. I don't know if original protobuffer is compatible (never tried it). We use a version forked by tvdzwan. If original is compatible, then it is no problem.

Why did you compile for *elec? We provide binaries for *elec. The protoc is only needed during compile and it doesn't take long to build it. To avoid building on those embedded distros we uses cross compilation.

**Comment by stefansaraev** [comment]
I personaly do compile for a stripped down fork of openelec. and I dont need/want lot of stuff supported by hyperion (using only fb/amlgrabber and that's all, no v4l, no protoservers and fancy stuff).

openelec / libreelec supports lot of different hardware, the general rule is "compile it yourself" instead of using pre-built binaries + lot of shared libs, no matter who builds them. for example. they do use static libqt4, no x11 (on rpi/imx6/amlogic). and, well, I do compile libusb as static library (OE/LE dont). that's just an example.

I helped LibreELEC people get the basics for compiling hyperion done (https://github.com/LibreELEC/LibreELEC.tv/pull/39), they have it nicely working as sa systemd service (users can install it via kodi's addonmanager). no chance they'll use binarries they did not build themselves

**Comment by redPanther** [comment]
ok, I didn't know the policies of libreelec people. I will see if original proto works.
I'm not happy that we have so much options - it is hard to give support when people compile by their own with none default options.

**Comment by stefansaraev** [comment]
using "original" protobuf is not a policy, if your fork is a must, they will use that. we are talking about the way it's built here ;)

**Comment by redPanther** [comment]
I've read the libreelec thread for this topic. Someone tried the find_package for protobuf. Then it should work ... I add possibility to use external proto, when my pending pr is merged (otherwise I get merge conflicts and I'm not in a mood for that)

can you tell me the exact cmake flags you compile for LE?

**Comment by stefansaraev** [comment]
LibreELEC (they use git: f64b6eb)
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/service/hyperion/package.mk#L51-L72

me (this is all I need, git: 667ee80)
https://github.com/stefansaraev/TB/blob/master/packages/addons/base-addons/service/hyperion/package.mk#L33-L50

moving to qt5 is no problem (I had cmake issues with qt5 last time I tried, but nothing that can't be fixed).

**Comment by redPanther** [comment]
I've made the PR regarding use of system protoc.
To use it add this cmake option:
```
-DUSE_SYSTEM_PROTO_LIBS=ON
```

**Pull request merged**
