### PR TITLE
New QT based udp driver

### PR DESCRIPTION
**Pull request by penfold42**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
New raw udp protocol device that uses the new generic udp shared driver

**2.** If this changes affect the .conf file. Please provide the changed section
deivce type "udpraw" is equivalent to protocol 0 in the old udp driver

**3.** Reference a issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
thx for sharing the code :-)
I saw some debug stuff in your file. I suggest to remove it, so we have cleaner code.

**Comment by penfold42** [comment]
done - please merge

**Comment by brindosch** [comment]
Thank you!
You introduced a new device name, to keep the old still available?
Is the old one deprecated or is this just a part of the old protocol possibility? Or a step in between?

**Comment by penfold42** [comment]
It's a step between - there are some blog posts using my old driver.

We need to port the tpm2.net driver to the new architecture and then we can the old driver.

If needed we can provide a compatibility layer

**Pull request merged**
