### PR TITLE
Apa102 fix if the led strip has more physical LEDs than you want to configure with hyperion

### PR DESCRIPTION
**Pull request by penfold42**
BEFORE:
If you have more physcial LEDs than defined in the "leds" "index" section of the config there is random junk added to the end of the strip.

WITH THIS FIX:
In the "device" section specify the number of physical leds with:
 "leds" : 212,
If this is greater than the number of led indexes, additional LEDs are set to black
If this is smaller than the number of led indexes, it is ignored

### CODE REVIEW

**Comment by brindosch** [comment]
@penfold42 
you changed the submodul commit id of the ws281x dependencies. Was this your intention?
I could no longer clone this deps :)

**Comment by penfold42** [comment]
Oops ... Not deliberately !

I wonder if this was related to my adding sk6812 support

**Comment by tociek** [comment]
Hi Guys,

Do I see it right, that the fix works only for APA102? Is there any reason why this could not be done for globally, for all types? (ws2801 has exactly the same problem)

**Comment by penfold42** [comment]
Correct 

Can you submit an issue in Hyperion.ng ?
We can try to fix it globally there

**Comment by tociek** [comment]
Sure, but what is Hyperion.ng? :)

**Comment by redPanther** [comment]
Hyperion v2.0 there is a new repository named hyperion.ng
We split that to develop future version besides current stable version

**Comment by penfold42** [comment]
https://github.com/hyperion-project/hyperion.ng/

**Pull request merged**
