### PR TITLE
create debian packages

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
create debian packages for clean install into your debian/*buntu system.

current compile looks like that (in short):

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -Wno-dev <other cmake options> ..
make -j 4
```
above thing still works, but now following is possible:

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -Wno-dev -DCMAKE_INSTALL_PREFIX=/usr -DPLATFORM=rpi-pwm ..
make -j 4
make -j 4 package

```

then a .deb will be generated. this package can be installed with:

`sudo dpkg -i hyperion-*-ambilight.deb`

the deb-postinstall script and deb infos aren't perfect yet, but after we can create .deb packages making it perfect shouldn't be hard.

I also add generation of rpm package for people who use suse, fedore, centos, ... it works in general, but postinstall script has to be filled with something usefull. (rpm currently deactivated)

BTW now `make install` works good. this won't be affecting your config or service file - only effects and the binaries. config and service files are handled by .deb/.rpm package

**2.** If this changes affect the .conf file. Please provide the changed section
**optional** changes:
path of effects: /usr/share/hyperion/effects
path of config file: /etc/hyperion/hyperion.config.json

**3.** Reference a issue (optional)

### CODE REVIEW

**Comment by penfold42** [comment]
Great work

**Comment by redPanther** [comment]
I will add a /opt compat layer with symlinks. So hypercon will work with this patch

**Comment by redPanther** [comment]
the debian package create symlinks for opt now. With this hypercon should work as expected

**Comment by brindosch** [comment]
This works? Great, so we could move immediately also with HyperCon to /etc/hyperion/ as storing location for all configs. As long we keep it compatible with older installs (just to a certain point)

I also don´t need to backup the hyperion.config.json during a update, which is great!

**Comment by redPanther** [comment]
we can add both effect paths:
/opt/hyperion/effects and /usr/share/hyperion/effects
to config. Then the opt compat layer forthe debian package is obsolete ...

**Comment by brindosch** [comment]
@redPanther 
https://github.com/hyperion-project/hyperion/pull/650/files#diff-af3b638bc2a3e6c650974192a53c7291R25
1 currently we provide just pi with pwm enabled (no user feedback required - no errors hehe).
So i consider to "change" this.
2. I should set SET ( DEFAULT_ZEROCONF  OFF )
to ON? and remove it from .sh

**Comment by redPanther** [comment]
1. not understand completely what you mean. pwm stuff is only for pi, because it is hardware pi specific. 

2. remove 
SET ( DEFAULT_ZEROCONF OFF ) and replace
${DEFAULT_ZEROCONF} with ON. zeroconf is not platform specific

**Comment by brindosch** [comment]
pi-pwm and pi
currently is used during crosscompile?

**Comment by redPanther** [comment]
no, that are 2 different things. see description of make_release function

# make_release <release name> <platform> [<cmake args ...>]
make_release rpi     rpi-pwm
means: make archive with _rpi name and use cmake platform flag "rpi-pwm"
there is also a rpi cmake platform flag, this is not used in crosscompile script and is same as rpi-pwm except ws281x pwm capability

**Pull request merged**
