### PR TITLE
start multiple hyperions

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
spawn multiple hyperiond when multiple configs given on command line

example

```
./hyperiond hyperion.hue.config.json hyperion.forwarder.config.json
```

if a given config is not found, it is ignored. If none of given configs exists, hyperion start is aborted with message.

if used for forwarder things, it is the best if config of forwarder is last in the list.
hyperiond instances started with 5 seconds delay to avoid race conditions.

Be aware that output of command line is a mess with more then one deamon. 

**2.** If this changes affect the .conf file. Please provide the changed section
no

**3.** Reference a issue (optional)

### CODE REVIEW

**Comment by penfold42** [comment]
Cool - should we consider a global instance name that is written with all the log output ?

**Comment by redPanther** [comment]
better eliminate all/most the output, "reduce to the max" ;-) I'm writing a logging/profiling facility for hyperion ...

**Comment by brindosch** [comment]
Wow! Great, now my script is useless ;)

I need to think about a script processing for setting this up (a way that is the same on all platforms)

**Comment by redPanther** [comment]
what is missing yet is that the instances watch each other ... I will tune it next days.

I'm think about some sort of auto configuration for the proto/json ports. Something like giving a port range in the config. The first hyperion process will set ports for all spawned hyperions in given range

**Comment by brindosch** [comment]
A auto-port configuration? Would be great! But how to handle this with forwarder config?

Additional: A field for the forwarder where you input the config names that should be started? To start with service is great, but may be better to handle from json

**Comment by redPanther** [comment]
initial control for parent-child process added. childs will exit when parent dies. This is important for using with scripts and services. Whats missing is the other way around or at least some detection by the parent that a child is gone. 

ATM implementation works, but hmm lets say it is a bit dirty. I will add commandline options (like in hyperion-x11) to hyperiond, then my hack (overwriting argv[0] for child process detection) can be removed. 

auto port stuff ... step by step, atm I'm thinking. json is definitly an option. Would be suitable, because I want to implement the restart thing from @Paulchen-Panther

**Comment by brindosch** [comment]
Would be quite handy! of course yes step by step. Don´t hurry. I just wanted to ask :)

**Comment by redPanther** [comment]
ok, now we have it.
- hyperiond has command line option support via getoptplusplus library (like hyperion-*).
- hack for spawned child detection removed and cleanly implemented via --parent command line argument
- if one of the hyperiond dies, all hyperiond will exit, regardless if they are parent or child process

BTW hyperiond is a mess. main function has 369 lines of code, this is to much! needs propper refactoring! Glad that I got a refactoring-refreshment-workshop last week ;-)

**Comment by brindosch** [comment]
nice one!
looks better now.

**Pull request merged**
