### PR TITLE
initialized led_string to prevent segfaults

### PR DESCRIPTION
**Pull request by wirkungsneutral**
**1.** Tell us something about your changes.
I got segfaults when using an SK6812 stripe with hyperiond on a raspberry 2B V1.1. The strandtest.py from the ws281x submodule worked flawlessly.  I've added a init for the led_string which fixes the issue for me. 

**3.** Reference a issue (optional)
I think this applies to #793

Thanks for your work. Hyperion is awesome.

### CODE REVIEW

**Comment by kevinpanaro** [comment]
I will test this tonight. I'll be shook if that's the only reason ws281x wasn't working for raspberry pi zero W. Thanks for looking into this.

**Comment by kevinpanaro** [comment]
I can confirm this is a working solution for the segfault issues I have been having. Nice find @wirkungsneutral.  :thumbsup:

**Comment by wirkungsneutral** [comment]
Thanks for testing 👍 Glad it worked for you

**Comment by chromoxdor** [comment]
Can someone explain me, how i can test this change?  
I really don´t know how to do this. Is there a simple way of install hyperion with this change?
:|

Thanks in advance...

**Comment by kevinpanaro** [comment]
@chromoxdor sure. 
So when you run [./install_hyperion.sh](https://github.com/hyperion-project/hyperion/blob/master/bin/install_hyperion.sh), that just pulls an already compiled hyperion binary from sourceforge and places it in the appropriate directories, as well as a couple other nice additional features. 

Now since something in the source has been changed we need to recompile that source. I compiled on my raspberry pi zero W, which took about 2 hours (boo), following [these instructions](https://github.com/hyperion-project/hyperion/blob/master/CompileHowto.txt). But you could also Cross Compile, using [these instructions](https://github.com/hyperion-project/hyperion/blob/master/CrossCompileHowto.txt), to compile everything on a much faster machine, and copy the hyperion binary over, once the compile completes.

Either way, in order to use this feature, you're going to have to compile it yourself, since its not merged. Following the instructions in the HowTo's, you should be able to compile.

**Comment by chromoxdor** [comment]
Thanks a lot! That's something for another day with a litte bit more time... :)

**Comment by chromoxdor** [comment]
Ok, so even with a little bit more time, it takes to much ... especially when you do this once in your lifetime.
If anybody successfully compiled it for the Raspberry pi 3b/b+, can you please send me a copy?
Thanks in advance!!!

**Comment by chromoxdor** [comment]
this is where i failed when i did the cross compiling. the missing packages are installed so i don´t know what to. also the howto for the crosscompiling seems to be not entirely correct -> [https://hyperion-project.org/threads/cross-compiling-issues-with-qt4-fw.804/](url)

`--  - Includes: /home/x/raspberrypi/rootfs/usr/include/libusb-1.0
--  - Libraries: /home/x/raspberrypi/rootfs/usr/lib/arm-linux-gnueabihf/libusb-1.0.so
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Using protobuf compiler: /home/x/hyperion/build-x86x64/bin/protoc
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libsrc/effectengine/CMakeLists.txt:2 (find_package)
`

**Comment by RickDB** [comment]
Nicely done and will merge it now, @brindosch used to make the binary versions so not sure when those will be up SF as he's taking a break from the project.

**Comment by YeonV** [comment]
BOOOM, awesome!
@kevinpanaro Thanks for linking that guide mate!!!!!
Confirming fully functional on a rpi3b+. (compile time ~5min)

**Comment by chromoxdor** [comment]
> BOOOM, awesome!
> @kevinpanaro Thanks for linking that guide mate!!!!!
> Confirming fully functional on a rpi3b+. (compile time ~5min)

Dear Yeon,
i´m am happy to hear, that it worked for you.
I tried it myself but i failed (two times)
Since i have a rpi3b+ too i was wondering if you could help me?
Could you send me the compiled files and give me maybe a brief instruction how to install?

Regards
Chromoxdor

**Comment by AlexBGoode** [comment]
Any chance to get the binary files already compiled for RPi3?

**Comment by Nightreaver** [comment]
this was fixed almost 6 month ago, and didnt make it into any binary... really?! 

Can we get a binary with that fix please!?

**Comment by tpmodding** [comment]
https://github.com/hyperion-project/hyperion/blob/master/CompileHowto.txt

here you go

**Comment by Nightreaver** [comment]
I did that.

I still dont see a reason why this can just be released as a binary. Rather have people spending hours, messing up their os's to install compilers and what not... for something thats so simple so solve.

**Comment by penfold42** [comment]
The reason is no one has had the time to sort out automated build and releases across 6 platforms.

**Comment by chromoxdor** [comment]
I tried to compile it myself and i failed.....several times  :/
Maybe somebody that already compiled binaries could provide them people like me  by uploading them somewhere.

**Comment by Nightreaver** [comment]
@chromoxdor which platform you are using? I compiled for Raspbian yesterday

**Comment by chromoxdor** [comment]
I need it for my raspi 3b with openelec/libreelec...

**Comment by Nightreaver** [comment]
@penfold42 with 6 platforms you mean the 6 "cmake" commands? Even tho 3 of them are RPi?

**Comment by penfold42** [comment]
Yes

But compiling for yourself is easy compared to releasing binaries for the public.

Now multiply out the permutations for OSMC, openelec, rasbian.
Then add in maintaining build or cross compile environments for each of them
Then add a couple of major version release for each.
Oh, you want OS native packages too?
Then add testing of the builds and the install process.

It gets out of control really quickly

**Comment by RickDB** [comment]
Yeah, there's a reason we don't have an active release maintainer anymore because it was too much work combined with the rework on Hyperion.ng

Right now we are focusing on getting Hyperion.ng stable with packaged releases (monthly / quarterly), not much left for that other than documentation and testing.
Guiding that alone and monitoring pull requests but we really could use a release maintainer again at some point to divide the workload.

**Pull request merged**
