### PR TITLE
Odroid C2 support

### PR DESCRIPTION
**Pull request by Starbix**

### CODE REVIEW

**Comment by Starbix** [comment]
I got that from here: https://github.com/hyperion-project/hyperion/issues/550 and here https://forum.odroid.com/viewtopic.php?t=19251&p=141063
I may also have to change to #define AMSTREAM_IOC_GET_VIDEO_DISABLE _IOR((_A_M), 0x48, int) but it works for me
I haven't tested 32 bit yet.

**Comment by jmccoy555** [comment]
Hi, I hope you don't mind me commenting here, but I think I have managed to also enable OpenPHT support by adding the following to the install script;

`elif [ $CPU_ODROIDC2 -eq 1 ] && [ $OS_OPENELEC -eq 1 ]; then
       HYPERION_RELEASE=https://raw.githubusercontent.com/Starbix/hyperion-files/master/release/hyperion_odroidc2_le.tar.gz`
        `OE_DEPENDECIES=https://raw.githubusercontent.com/Starbix/hyperion-files/master/release/hyperion.deps.libreelec-odroid.tar.gz`

Strangely it puts the dependencies in /hyperion/bin/hyperion.deps.libreelec-odroid I did spin up a copy of Koidi and got the same result......

A quick copy to /hyperion/bin, chown and a reboot appears to sort it out though. 

Would be happy to try and create a PR once this is merged, unless it can be combined? 

Only issue now is I have ws2801 which appear to be unsupported (according to the log file), @Starbix could you let me know what you have got running with your build so I can test?

**Comment by penfold42** [comment]
Could you try porting hyperion.ng ?

The spi support is probably because it only enables spi for raspberry pi.
If the odroid has a normal spi kernel driver it should just work once you get CMake to do the right thing.

If the kernel supports a dma spi transfers ws2812 should also just work

**Comment by jmccoy555** [comment]
I think I could give that a go..... so basically building from hyperion.ng, rather than this one? 

I've had a quick look around on the forums, and it would appear that the C2 doesn't have true spi, but it does look like people have got it to work with the ws28xx. Or the other option of USBASP might be easier.......

**Comment by Starbix** [comment]
I'm not sure about the WS2801. But yes, the Odroid C2 doesn't support true SPI, only sw emulated, which is too slow for LEDs, I just use an Arduino over USB.

**Comment by penfold42** [comment]
Ws281x are really timing sensitive but ws2801 use a normal spi interface with data and clock.

The 2801 should work ok with software spi

**Comment by penfold42** [comment]
Anything interesting in dmesg ?

**Comment by jmccoy555** [comment]
I added the service manually;

[Unit]
Description=Hyperion Systemd service

[Service]
Type=simple
User=root
Group=root
UMask=007
ExecStart=/storage/hyperion/bin/hyperiond /storage/.config/hyperion.config.json
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target


Systemctl - Enable, Start, Status;


● hyperion.service - Hyperion Systemd service
   Loaded: loaded (/storage/.config/system.d/hyperion.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-02-27 02:45:35 UTC; 1 years 1 months ago
  Process: 540 ExecStart=/storage/hyperion/bin/hyperiond /storage/.config/hyperion.config.json (code=exited, status=127)
 Main PID: 540 (code=exited, status=127)

Feb 27 02:45:34 OpenPHT-Embedded systemd[1]: hyperion.service: Failed with result 'exit-code'.
Feb 27 02:45:35 OpenPHT-Embedded systemd[1]: hyperion.service: Service hold-off time over, scheduling restart.
Feb 27 02:45:35 OpenPHT-Embedded systemd[1]: Stopped Hyperion Systemd service.
Feb 27 02:45:35 OpenPHT-Embedded systemd[1]: hyperion.service: Start request repeated too quickly.
Feb 27 02:45:35 OpenPHT-Embedded systemd[1]: Failed to start Hyperion Systemd service.
Feb 27 02:45:35 OpenPHT-Embedded systemd[1]: hyperion.service: Unit entered failed state.
Feb 27 02:45:35 OpenPHT-Embedded systemd[1]: hyperion.service: Failed with result 'exit-code'.


journalctl -xe;

Apr 07 15:00:44 OpenPHT-Embedded hyperiond[677]: /storage/hyperion/bin/hyperiond: error while loading shared libraries: libQtNetwork.so.4: cannot open shared object file: No such file or directory
Apr 07 15:00:44 OpenPHT-Embedded systemd[1]: hyperion.service: Main process exited, code=exited, status=127/n/a
Apr 07 15:00:44 OpenPHT-Embedded systemd[1]: hyperion.service: Unit entered failed state.
Apr 07 15:00:44 OpenPHT-Embedded systemd[1]: hyperion.service: Failed with result 'exit-code'.
Apr 07 15:00:44 OpenPHT-Embedded kernel: ERROR::handle_hc_nak_intr:1306: Can not read device info from hub.We take it error
Apr 07 15:00:44 OpenPHT-Embedded kernel: ERROR::handle_hc_nak_intr:1306: Can not read device info from hub.We take it error
Apr 07 15:00:44 OpenPHT-Embedded kernel: ERROR::handle_hc_nak_intr:1306: Can not read device info from hub.We take it error
Apr 07 15:00:44 OpenPHT-Embedded kernel: ERROR::handle_hc_nak_intr:1306: Can not read device info from hub.We take it error
Apr 07 15:00:44 OpenPHT-Embedded kernel: ERROR::handle_hc_nak_intr:1306: Can not read device info from hub.We take it error
Apr 07 15:00:44 OpenPHT-Embedded systemd[1]: hyperion.service: Service hold-off time over, scheduling restart.
Apr 07 15:00:44 OpenPHT-Embedded systemd[1]: Stopped Hyperion Systemd service.
Apr 07 15:00:44 OpenPHT-Embedded systemd[1]: Started Hyperion Systemd service.


Looks like libQtNetwork.so.4 is missing???

**Pull request closed without merging**
